<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>windows-preventer</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsPreventer.Core\WindowsPreventer.Core.csproj" />
    <ProjectReference Include="..\WindowsPreventer.Licensing\WindowsPreventer.Licensing.csproj" />
  </ItemGroup>
</Project>
